<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.9" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
	<PackageReference Include="Sentry.AspNetCore" Version="6.6.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Localization\API.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>API.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Resources\Localization\API.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>API.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kvm.Contracts\Kvm.Contracts.csproj" />
  </ItemGroup>

</Project>
