//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class API {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal API() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Control.Resources.Localization.API", typeof(API).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Management API authentication failed 的本地化字符串。
        /// </summary>
        internal static string admin_authentication_failed {
            get {
                return ResourceManager.GetString("admin_authentication_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Request 的本地化字符串。
        /// </summary>
        internal static string bad_requests {
            get {
                return ResourceManager.GetString("bad_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cluster request failed 的本地化字符串。
        /// </summary>
        internal static string cluster_request_failed {
            get {
                return ResourceManager.GetString("cluster_request_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string display_flag {
            get {
                return ResourceManager.GetString("display_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default(en-us) 的本地化字符串。
        /// </summary>
        internal static string display_name {
            get {
                return ResourceManager.GetString("display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idempotency-Key was already used for a different request. 的本地化字符串。
        /// </summary>
        internal static string idempotency_conflict {
            get {
                return ResourceManager.GetString("idempotency_conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal server error. 的本地化字符串。
        /// </summary>
        internal static string internal_error {
            get {
                return ResourceManager.GetString("internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type must be linux or open-vswitch. 的本地化字符串。
        /// </summary>
        internal static string invalid_bridge_type {
            get {
                return ResourceManager.GetString("invalid_bridge_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idempotency-Key is required and must be at most 128 characters. 的本地化字符串。
        /// </summary>
        internal static string invalid_idempotency_key {
            get {
                return ResourceManager.GetString("invalid_idempotency_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action must be start, shutdown, reboot, or force-off. 的本地化字符串。
        /// </summary>
        internal static string invalid_power_action {
            get {
                return ResourceManager.GetString("invalid_power_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The supplied value is invalid. 的本地化字符串。
        /// </summary>
        internal static string invalid_value {
            get {
                return ResourceManager.GetString("invalid_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 waitSeconds must be between 0 and 30. 的本地化字符串。
        /// </summary>
        internal static string invalid_wait_seconds {
            get {
                return ResourceManager.GetString("invalid_wait_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method not allowed. 的本地化字符串。
        /// </summary>
        internal static string method_not_allowed {
            get {
                return ResourceManager.GetString("method_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation accepted. 的本地化字符串。
        /// </summary>
        internal static string operation_accepted {
            get {
                return ResourceManager.GetString("operation_accepted", resourceCulture);
            }
        }
        
        internal static string operation_owner_lost {
            get {
                return ResourceManager.GetString("operation_owner_lost", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Operation queue is full. 的本地化字符串。
        /// </summary>
        internal static string operation_queue_full {
            get {
                return ResourceManager.GetString("operation_queue_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid request parameters 的本地化字符串。
        /// </summary>
        internal static string request_error {
            get {
                return ResourceManager.GetString("request_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource not found 的本地化字符串。
        /// </summary>
        internal static string resource_not_found {
            get {
                return ResourceManager.GetString("resource_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Found 的本地化字符串。
        /// </summary>
        internal static string route_not_found {
            get {
                return ResourceManager.GetString("route_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Sock Fail 的本地化字符串。
        /// </summary>
        internal static string sock_remove_fail {
            get {
                return ResourceManager.GetString("sock_remove_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string success_message {
            get {
                return ResourceManager.GetString("success_message", resourceCulture);
            }
        }
    }
}
